# Generated by Django 5.2.6 on 2025-09-28 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên điểm đến')),
                ('country', models.CharField(max_length=100, verbose_name='Quốc gia')),
                ('city', models.CharField(max_length=100, verbose_name='Thành phố')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('best_time_to_visit', models.CharField(max_length=200, verbose_name='Thời điểm tốt nhất')),
                ('average_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Chi phí trung bình/ngày (USD)')),
                ('rating', models.FloatField(default=0, verbose_name='Đánh giá')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Điểm đến',
                'verbose_name_plural': 'Điểm đến',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='ID phiên')),
                ('user_message', models.TextField(verbose_name='Tin nhắn người dùng')),
                ('bot_response', models.TextField(verbose_name='Phản hồi bot')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử chat',
                'verbose_name_plural': 'Lịch sử chat',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên điểm tham quan')),
                ('category', models.CharField(choices=[('historical', 'Lịch sử'), ('natural', 'Thiên nhiên'), ('cultural', 'Văn hóa'), ('adventure', 'Phiêu lưu'), ('entertainment', 'Giải trí')], max_length=100, verbose_name='Loại hình')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Giá vé (USD)')),
                ('opening_hours', models.CharField(max_length=200, verbose_name='Giờ mở cửa')),
                ('rating', models.FloatField(default=0, verbose_name='Đánh giá')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='chatbot.destination')),
            ],
            options={
                'verbose_name': 'Điểm tham quan',
                'verbose_name_plural': 'Điểm tham quan',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên khách sạn')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('star_rating', models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], verbose_name='Hạng sao')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Giá/đêm (USD)')),
                ('amenities', models.TextField(help_text='Các tiện nghi cách nhau bởi dấu phẩy', verbose_name='Tiện nghi')),
                ('rating', models.FloatField(default=0, verbose_name='Đánh giá')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='chatbot.destination')),
            ],
            options={
                'verbose_name': 'Khách sạn',
                'verbose_name_plural': 'Khách sạn',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhà hàng')),
                ('cuisine_type', models.CharField(max_length=100, verbose_name='Loại ẩm thực')),
                ('price_range', models.CharField(choices=[('$', 'Bình dân'), ('$$', 'Trung bình'), ('$$$', 'Cao cấp'), ('$$$$', 'Sang trọng')], max_length=20, verbose_name='Mức giá')),
                ('specialty', models.TextField(verbose_name='Món đặc trưng')),
                ('rating', models.FloatField(default=0, verbose_name='Đánh giá')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='chatbot.destination')),
            ],
            options={
                'verbose_name': 'Nhà hàng',
                'verbose_name_plural': 'Nhà hàng',
            },
        ),
    ]
