# Generated by Django 5.2.6 on 2025-10-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
    ]
